### ISSUE TITLE
Usage of middleware and at least one interceptor.

### ISSUE THREAD

**Issue by disoversity** [bamboozlegui/Karma#43]

**Comment by disoversity** [comment]
https://www.youtube.com/watch?v=iR_PNKtJENE

**Comment by bamboozlegui** [comment]
So, I started writing middleware for logging (issue #45), that way we can ace 2 requirements at once!

You can check it out here: [use-middleware-logging](https://github.com/bamboozlegui/Karma/tree/use-middleware-logging).

I will try to make it so we can log when a user posts item, we get basic info and status code of the request. That way, if something goes wrong, we can check the logs.

Also, currently, the logger shows info in console.

If you have any questions/concerns or suggestions, feel free to write them here.
